--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/Hebbinkpro/PocketMap
build-by-default: true
branches:
  - main
projects:
  PocketMap:
    path: ""
    libs:
      - src: Hebbinkpro/pmmp-webserver/pmmp-webserver
        version: 0.3.7
      - src: HimbeersaftLP/LibSkin/LibSkin
        version: 2.0.1
      - src: Paroxity/Commando/Commando
        version: 3.1.0
      - src: Muqsit/SimplePacketHandler/SimplePacketHandler
        version: 0.1.3
    lint:
      phpstan: false
...
