name: PocketMap
main: Hebbinkpro\PocketMap\PocketMap
version: 0.4.5
api: [ 5.8.1 ]
load: STARTUP
author: Hebbinkpro
description: A dynamic world map for PocketMine-MP
website: https://github.com/Hebbinkpro/PocketMap

permissions:
  pocketmap.cmd:
    description: Allows to execute pocketmap commands
    default: true
  pocketmap.cmd.render:
    description: Allows to render the world map
    default: op
  pocketmap.cmd.reload:
    description: Allows to reload some parts of the plugin
    default: op