name: PocketMap
main: Hebbinkpro\PocketMap\PocketMap
version: 0.4.5
api: [ 5.8.1 ]
load: STARTUP
author: Hebbinkpro
description: A dynamic world map for PocketMine-MP
website: https://github.com/Hebbinkpro/PocketMap

permissions:
  pocketmap.cmd:
    description: Allows to execute pocketmap commands
    default: true
  pocketmap.cmd.render:
    description: Allows to execute the render command
    default: op
  pocketmap.cmd.reload:
    description: Allows to execute the reload command
    default: op
  pocketmap.cmd.reload.config:
    description: Allows to execute the reload config command
    default: op
  pocketmap.cmd.reload.web:
    description: Allows to execute the reload web command
    default: op
  pocketmap.cmd.reload.data:
    description: Allows to execute the reload data command
    default: op
  pocketmap.cmd.marker:
    description: Allows to execute the marker command
    default: op
  pocketmap.cmd.marker.add:
    description: Allows to execute the marker add command
    default: op
  pocketmap.cmd.marker.remove:
    description: Allows to execute the marker remove command
    default: op
