name: PocketMap
main: Hebbinkpro\PocketMap\PocketMap
version: 0.4.5
api: [ 5.8.1 ]
load: STARTUP
author: Hebbinkpro
description: A dynamic world map for PocketMine-MP
website: https://github.com/Hebbinkpro/PocketMap

permissions:
  pocketmap.cmd:
    description: Allows to execute pocketmap commands
    default: op

commands:
  reload:
    description: Reloads the PocketMap config and web files
    permission: pocketmap.cmd

  render:
    description: Render a specific region
    permission: pocketmap.cmd
